sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-qingdao.aliyuncs.com
    access-key-id: LTAI5tKf6jtNs16tV98GbcKG
    access-key-secret: nllfJgj05MqF1AbIyiZNjT1IDYOmqg
    bucket-name: sky-kryon
  redis:
    host: localhost
    port: 6379
    password: 123456
